import React from 'react';
import { FileText, Download, FileCheck, Share2 } from 'lucide-react';

export const ReportsPage: React.FC = () => {
  const reports = [
    { title: 'National MPLADS Risk Intelligence Annual Summary 2024-25', date: '01 May 2026', type: 'Executive PDF', size: '4.2 MB' },
    { title: 'State-wise Cost Anomaly & Price Benchmarking Report', date: '28 Apr 2026', type: 'Analytical PDF', size: '2.8 MB' },
    { title: 'Duplicate Works & Spatial Proximity Verification Register', date: '20 Apr 2026', type: 'Audit Register', size: '6.1 MB' },
    { title: 'Quarterly Physical Progress & Delay Forecast', date: '15 Apr 2026', type: 'Forecast Report', size: '1.9 MB' }
  ];

  return (
    <div className="space-y-5 pb-8">
      <div className="border-b border-slate-200 pb-3">
        <h1 className="text-xl font-extrabold text-navy-900 tracking-tight">
          AI Monitoring & Audit Reports
        </h1>
        <p className="text-xs text-slate-500 font-medium mt-0.5">
          Download automated PDF and spreadsheet intelligence reports generated by the MPLADS AI engine
        </p>
      </div>

      <div className="space-y-3">
        {reports.map((r, i) => (
          <div key={i} className="bg-white border border-slate-200 rounded-lg p-4 flex items-center justify-between hover:border-slate-300 transition-colors">
            <div className="flex items-center gap-3">
              <div className="p-2.5 bg-navy-900 text-amber-400 rounded-md">
                <FileText className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-sm font-bold text-slate-800">{r.title}</h3>
                <div className="flex items-center gap-3 text-xs text-slate-500 font-medium mt-0.5">
                  <span>Generated: {r.date}</span>
                  <span>•</span>
                  <span>Type: {r.type}</span>
                  <span>•</span>
                  <span>Size: {r.size}</span>
                </div>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <button className="flex items-center gap-1.5 bg-navy-900 text-white font-bold text-xs px-3 py-1.5 rounded hover:bg-navy-800 transition-colors">
                <Download className="w-3.5 h-3.5" />
                <span>Download</span>
              </button>
              <button className="p-1.5 border border-slate-300 rounded text-slate-600 hover:bg-slate-100">
                <Share2 className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
